// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/purchase.proto

package purchase

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Purchase service

func NewPurchaseEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Purchase service

type PurchaseService interface {
	Start(ctx context.Context, in *User, opts ...client.CallOption) (*Purch, error)
	Implementation(ctx context.Context, in *Details, opts ...client.CallOption) (*Order, error)
}

type purchaseService struct {
	c    client.Client
	name string
}

func NewPurchaseService(name string, c client.Client) PurchaseService {
	return &purchaseService{
		c:    c,
		name: name,
	}
}

func (c *purchaseService) Start(ctx context.Context, in *User, opts ...client.CallOption) (*Purch, error) {
	req := c.c.NewRequest(c.name, "Purchase.Start", in)
	out := new(Purch)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseService) Implementation(ctx context.Context, in *Details, opts ...client.CallOption) (*Order, error) {
	req := c.c.NewRequest(c.name, "Purchase.Implementation", in)
	out := new(Order)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Purchase service

type PurchaseHandler interface {
	Start(context.Context, *User, *Purch) error
	Implementation(context.Context, *Details, *Order) error
}

func RegisterPurchaseHandler(s server.Server, hdlr PurchaseHandler, opts ...server.HandlerOption) error {
	type purchase interface {
		Start(ctx context.Context, in *User, out *Purch) error
		Implementation(ctx context.Context, in *Details, out *Order) error
	}
	type Purchase struct {
		purchase
	}
	h := &purchaseHandler{hdlr}
	return s.Handle(s.NewHandler(&Purchase{h}, opts...))
}

type purchaseHandler struct {
	PurchaseHandler
}

func (h *purchaseHandler) Start(ctx context.Context, in *User, out *Purch) error {
	return h.PurchaseHandler.Start(ctx, in, out)
}

func (h *purchaseHandler) Implementation(ctx context.Context, in *Details, out *Order) error {
	return h.PurchaseHandler.Implementation(ctx, in, out)
}
